# Generated by Django 6.0 on 2025-12-24 06:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='security_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='security_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='selfie_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_id',
            field=models.CharField(default='LOAN-000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('completed', 'Completed')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
