# Generated by Django 5.2.7 on 2025-12-25 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_alter_loanapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_country', models.CharField(max_length=100)),
                ('recipient_bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('transfer_type', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal'), ('other', 'Other')], default='bank_transfer', max_length=50)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Money Transfer',
                'verbose_name_plural': 'Money Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.moneytransfer')),
            ],
            options={
                'verbose_name': 'Transfer Status History',
                'verbose_name_plural': 'Transfer Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
