# Generated by Django 5.2.7 on 2025-12-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='sender_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
